### ISSUE TITLE
CommonCoordinateSpaceVersion link to CommonCoordinateSpace

### ISSUE THREAD

**Issue by bendichter** [openMetadataInitiative/openMINDS_documentation#23]
Unless I am reading this wrong (which is certainly possible) it looks like you have a CommonCoordinateSpaceVersion spec and a CommonCoordinateSpace spec but there is no linkage between the two. I propose adding a is_version_of attribute to CommonCoordinateSpaceVersion pointing to a CommonCoordinateSpace.

**Comment by ehennestad** [comment]
If you look at the CommonCoordinateSpace schema in the SANDS model, it has a hasVersion property:

https://github.com/openMetadataInitiative/openMINDS_SANDS/blob/3a542916b22c0b8f4b6dd64c4bba1658614bf78b/schemas/atlas/commonCoordinateSpace.schema.tpl.json#L32-L39

Links in the openMINDS schemas are typically one-directional, and then graph databases can implement reverse links for instances. Lyuba can fill inn more details on this!

**Comment by apdavison** [comment]
@ehennestad just beat me to it, but since I just finished typing this I'll post it anyway!

There is an explicit `hasVersion` link from CommonCoordinateSpace to CCSV: https://openminds-documentation.readthedocs.io/en/latest/schema_specifications/SANDS/atlas/commonCoordinateSpace.html#hasversion

There is an implicit reverse link, which [we haven't formally named](https://github.com/openMetadataInitiative/openMINDS/blob/81e1f90e4e59fe13147a9169691f90a259734e42/vocab/properties.json#L5988) (naming reverse links is still a TODO), although **fairgraph** does indeed use the name [`is_version_of`](https://github.com/HumanBrainProject/fairgraph/blob/8c2bd4be02c384aeea41abaf900526afe8e867a5/fairgraph/openminds/sands/atlas/common_coordinate_space_version.py#L362) as you suggest.

**Comment by bendichter** [comment]
ok cool, thanks!
